
version: 2
jobs:
  install_requirements:
    docker:
     - image: circleci/python:3.8.5
    working_directory: ~/cheqmate-backend
    steps:
     - checkout
     - run:
         name: Install requirements
         command: |
            pip install -r requirements.txt 
